-- liquibase formatted sql

-- changeset hmz_v:1745220836935-1
CREATE TABLE "category" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "title" TEXT, "slug" TEXT, "description" TEXT, CONSTRAINT "category_pkey" PRIMARY KEY ("id"));

-- changeset hmz_v:1745220836935-2
ALTER TABLE "posts" ADD "cat_id" BIGINT;

-- changeset hmz_v:1745220836935-3
ALTER TABLE "posts" ADD CONSTRAINT "posts_cat_id_fkey" FOREIGN KEY ("cat_id") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset hmz_v:1745220836935-4
ALTER TABLE "posts" DROP COLUMN "ccat_id";

