-- liquibase formatted sql

-- changeset hmz_v:1745221378333-1
CREATE TABLE "city" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "title" TEXT, "slug" TEXT, "desc" TEXT, CONSTRAINT "city_pkey" PRIMARY KEY ("id"));

-- changeset hmz_v:1745221378333-2
ALTER TABLE "posts" ADD "city_id" BIGINT;

-- changeset hmz_v:1745221378333-3
ALTER TABLE "posts" ADD CONSTRAINT "posts_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "city" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

